Stringify response before json.loads (#91)
* Stringify response before json.loads

This fixes the "the json object must be str, not 'bytes'" error that happens on line 145.

Sample error before fix:
```
Traceback (most recent call last):
  File "(...)/twitter.py", line 53, in <module>
    async_data = LineItem.async_stats_job_data(account, async_stats_job_result['url'])
  File "(...)/venv/lib/python3.5/site-packages/twitter_ads/resource.py", line 261, in async_stats_job_data
    raw_body=True, stream=True).perform()
  File "(...)/venv/lib/python3.5/site-packages/twitter_ads/http.py", line 73, in perform
    response = self.__oauth_request()
  File "(...)/venv/lib/python3.5/site-packages/twitter_ads/http.py", line 103, in __oauth_request
    body=response.raw, raw_body=raw_response_body)
  File "(...)/venv/lib/python3.5/site-packages/twitter_ads/http.py", line 145, in __init__
    self._body = json.loads(raw_response_body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

* Update for unicode convention

The reason this was erroring out is because some of the responses are strings and the others are bytes. By only decoding in the case of bytes we get valid python -> json objects from `LineItem.async_stats_job_data(...)` instead of huge line of bytes.

* Edited indentation

* Python 3.x compatibility

* remove unnecessary changes